### ISSUE TITLE
Tokens are locked

### ISSUE THREAD

**Issue by MaxSaleh** [eric48906/Discord-Token-Generator-2022#1]
Hello, when I try using it the tokens are locked and when I try using a vpn and generating a new token they are still locked.

**Comment by eric48906** [comment]
You would need to add proxy support. I might update it in the future.

**Comment by eric48906** [comment]
You would need to add proxy support,
I did add a disclaimer to the README that the generator is generating locked accounts due to a new discord patch.

I might update it in the future.

**Comment by MaxSaleh** [comment]
what's the best proxy you would use for this?
