### ISSUE TITLE
ModuleNotFoundError: No module named 'discord_build_info_py'

### ISSUE THREAD

**Issue by ssh-tapishnu** [eric48906/Discord-Token-Generator-2022#9]
py main.py
Traceback (most recent call last):
  File "C:\Users\Tapishnu dey\Desktop\Discord-Token-Generator-2022-main\main.py", line 2, in <module>
    from discord_build_info_py import getClientData
ModuleNotFoundError: No module named 'discord_build_info_py'

**Comment by cintagram** [comment]
he didnt released yet

**Comment by eric48906** [comment]
That package was discontinued, star it and wait for the new version @ 50 stars
